# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Windows Application

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies from Pipfile.lock
      run: |
        pip install pipenv
        pipenv install

    - name: Build with PyInstaller
      run: |
        pipenv run pyinstaller -w --onefile --console --name="Ambient Sensor" "Ambient Sensor.py" --distpath apps
        pipenv run pyinstaller --onefile --console --name="CredentialsInstaller" "Credentials Installer.py" --distpath apps
        pipenv run pyinstaller --onefile --console --name="Identifier Monitor" "Identifier Monitor.py" --distpath apps
        pipenv run pyinstaller --onefile --console --name="Message Size Optimizer" "Message Size Optimizer.py" --distpath apps
        pipenv run pyinstaller -w --onefile --name "Virtual Sensors" "Virtual Sensors.py" --distpath apps

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MQTT
        path: "apps/*"
