# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies from Pipfile.lock
      run: |
        pip install pipenv
        pipenv install
    
    - name: Build with PyInstaller
      run: |
        pipenv run pyinstaller -w --onefile --console file.py --distpath apps
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        path: "apps/*"
