# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies from Pipfile.lock
      run: |
        pip install pipenv
        pipenv install
        pipenv shell
#         pip install --no-deps --ignore-installed -r <(pipenv lock -r)
        
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install flake8 pytest
#         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --console --name="MQTT Message Size Optimizer" "Message Size Optimizer.py"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        path: "dist/Message Size Optimizer.py"
